### ISSUE TITLE
how can i solve this problem

### ISSUE THREAD

**Issue by ghost** [seowings/netlify-status-wordpress#1]
4:14:35 PM: "build.command" failed                                        
4:14:35 PM: ────────────────────────────────────────────────────────────────
4:14:35 PM: ​
4:14:35 PM:   Error message
4:14:35 PM:   Command failed with exit code 1: python src/main.py (https://ntl.fyi/exit-code-1)
4:14:35 PM: ​
4:14:35 PM:   Error location
4:14:35 PM:   In build.command from netlify.toml:
4:14:35 PM:   python src/main.py
4:14:37 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2 (https://ntl.fyi/exit-code-2)
4:14:35 PM: ​
4:14:35 PM:   Resolved config
4:14:35 PM:   build:
4:14:35 PM:     command: python src/main.py
4:14:35 PM:     commandOrigin: config
4:14:35 PM:     environment:
4:14:35 PM:       - INCOMING_HOOK_BODY
4:14:35 PM:       - INCOMING_HOOK_TITLE
4:14:35 PM:       - INCOMING_HOOK_URL
4:14:35 PM:     publish: /opt/build/repo/output
4:14:35 PM:     publishOrigin: config
4:14:36 PM: Caching artifacts
4:14:36 PM: Started saving build plugins
4:14:36 PM: Finished saving build plugins
4:14:36 PM: Started saving pip cache
4:14:36 PM: Finished saving pip cache
4:14:36 PM: Started saving emacs cask dependencies
4:14:36 PM: Finished saving emacs cask dependencies
4:14:36 PM: Started saving maven dependencies
4:14:36 PM: Finished saving maven dependencies
4:14:36 PM: Started saving boot dependencies
4:14:36 PM: Finished saving boot dependencies
4:14:36 PM: Started saving rust rustup cache
4:14:36 PM: Finished saving rust rustup cache
4:14:36 PM: Started saving go dependencies
4:14:36 PM: Finished saving go dependencies
4:14:37 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
4:14:37 PM: Failing build: Failed to build site
4:14:37 PM: Finished processing build request in 17.434s

**Comment by seowings** [comment]
Have you configured the plugin on your wordpress website? I hope you have seen the video where I have explained them in detail.

https://youtu.be/cYk9YEJv82Q

**Comment by ghost** [comment]
**I have applied everything in the video, but I'm still experiencing the same problem.**


![Netlify Status ‹ WP — WordPress](https://github.com/serpwings/netlify-status-wordpress/assets/87495968/5892dafa-891c-4ad8-b992-484176346ef2)


![Generate Static Site ‹ WP — WordPress](https://github.com/serpwings/netlify-status-wordpress/assets/87495968/537c5ec9-2bfb-4932-8af7-551aa9fb1bd8)


![Simply Static Settings ‹ WP — WordPress](https://github.com/serpwings/netlify-status-wordpress/assets/87495968/72d5ec06-73f4-46d4-81e5-b9b4af3572c8)


![Simply Static Settings ‹ WP — WordPress (1)](https://github.com/serpwings/netlify-status-wordpress/assets/87495968/8ce7fc36-262c-43ee-95f1-cb425b2bfbbc)


![Simply Static Settings ‹ WP — WordPress (2)](https://github.com/serpwings/netlify-status-wordpress/assets/87495968/398e73f1-07a8-4bb3-a635-6a5d6f05382a)

**Comment by seowings** [comment]
Can you check if you have correctly created netlify hook for your desired project? I will dig it for more details and then get back to you.

**Comment by ghost** [comment]
Okey thank you

**Comment by seowings** [comment]
I have done several tests and found no issue with this approach. All deployments are working fine. Have you also cross checked all configurations on your side?
